# Generated by Django 3.1.7 on 2021-03-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviefile',
            options={'ordering': ('path',), 'verbose_name': 'Movie file', 'verbose_name_plural': 'Movie files'},
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
