# Generated by Django 3.1.7 on 2021-03-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210307_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='probed_bitrate',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
