# Generated by Django 3.1.7 on 2021-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviefile_probed_bitrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='force_convert',
            field=models.BooleanField(default=False),
        ),
    ]
